#!/bin/bash

# Executar o script de instalação
echo "Executando script postinst..."

# Verificar se o script está sendo executado como root
if [ "$(id -u)" -eq 0 ]; then
    # Se for root, altere o .bashrc do usuário especificado por $SUDO_USER
    user_home=$(eval echo "~$SUDO_USER")

    echo '# SCRIPT TO ADD EMOJI' >> "$user_home/.bashrc"
    echo 'git() {' >> "$user_home/.bashrc"
    echo "    $user_home/../../usr/bin/.commit-emoji-adder/git \"\$@\"" >> "$user_home/.bashrc"
    echo '}' >> "$user_home/.bashrc"
	source "$user_home/.bashrc"
else
    # Se não for root, adicionar diretamente no .bashrc do usuário atual
    echo '# SCRIPT TO ADD EMOJI' >> "$HOME/.bashrc"
    echo 'git() {' >> "$HOME/.bashrc"
    echo "    $HOME/../../usr/bin/.commit-emoji-adder/git \"\$@\"" >> "$HOME/.bashrc"
    echo '}' >> "$HOME/.bashrc"
	source "$HOME/.bashrc"
fi

# Garantir que o script `postinst` execute com sucesso
exit 0

