#!/bin/bash

# Remove configurações do .bashrc

# Verificar se o script está sendo executado como root
if [ "$(id -u)" -eq 0 ]; then
    # Se for root, altere o .bashrc do usuário especificado por $SUDO_USER
    user_home=$(eval echo "~$SUDO_USER")

	sed -i '/# SCRIPT TO ADD EMOJI/d' "$user_home/.bashrc"
	sed -i '/git() {/,+2d' "$user_home/.bashrc"
    
else
    # Se não for root, adicionar diretamente no .bashrc do usuário atual
	sed -i '/# SCRIPT TO ADD EMOJI/d' "$HOME/.bashrc"
	sed -i '/git() {/,+2d' "$HOME/.bashrc"

fi

exit 0

